# 代理配置示例
proxy:
  enabled: true  # 是否启用代理
  proxies:
    # HTTP代理示例
    - host: 192.168.1.99
      port: 20171
      type: HTTP
      username: ""  # 如果代理需要认证
      password: ""

    # SOCKS代理示例
    - host: 192.168.1.99
      port: 20170
      type: SOCKS
      username: ""
      password: ""

    # 更多代理可以继续添加
    # - host: proxy3.example.com
    #   port: 3128
    #   type: HTTP

# 如果不使用代理，设置为：
# proxy:
#   enabled: false
#   proxies: []

